# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34e09a5dbc1bc7462f6fe5796e54a5be"
application_url = "https://choir-sodium-position-precision.trycloudflare.com"
embedded = true
name = "White-Glove-Popup"
handle = "white-glove-popup"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://choir-sodium-position-precision.trycloudflare.com/auth/callback",
  "https://choir-sodium-position-precision.trycloudflare.com/auth/shopify/callback",
  "https://choir-sodium-position-precision.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "bits-development.myshopify.com"
automatically_update_urls_on_dev = true
